version: "3"
services:
  db:
    image: postgres:11
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always

  odoo:
    build: ./odoo
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: -- --dev=reload
    volumes:
      - ~/custom_addons:/mnt/custom_addons
      - ./etc:/etc/odoo
    restart: always
